#  Table of Contents for 4.8 Grouping data and aggregating variables
    Importing libraries, set path, import files (ords_prods_merge_newvariable.pkl)
    Lesson: Get a subset of df of 1,000,000 - check shape, head
                Group by product name
                Group on department_id by using the mean, max and min on order_number
            On full df, create a new column max_order defined by grouping the user_id with the max count of order_number 
                Check the head for 100 rows - use code to allow jupyter to show all 100 rows
            Assign loyalty values to the max_order column where 
                if the max is above 40 the string is 'loyal customer', 
                if more than ten and equal/less than 40 then 'regular customer', 
                and if less than 10 then 'new customer"
                The new column is loyalty_flag
                View its counts
                View the head of columns 'user_id', 'loyalty_flag', 'order_number'
            Save

# Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import os

# Set path

In [2]:
path = r'C:\Users\valev\Desktop\0325 Instacart Basket Analysis'

# Import files

In [3]:
df_ords_prods_merge = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'ord_prods_merge_newvariable.pkl' ))

# Get a subset df

In [4]:
df = df_ords_prods_merge[:1000000]

In [5]:
df.shape

(1000000, 18)

In [6]:
df.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day
0,1,Chocolate Sandwich Cookies,61,19,5.800781,1107,38259,2,1,11,7.0,7,0,both,Mid-range product,Regularly busy,Next_busiest_day,Most orders
1,1,Chocolate Sandwich Cookies,61,19,5.800781,5319,196224,65,1,14,1.0,3,1,both,Mid-range product,Regularly busy,Next_busiest_day,Most orders
2,1,Chocolate Sandwich Cookies,61,19,5.800781,7540,138499,8,0,14,7.0,4,1,both,Mid-range product,Busiest day,Busiest day,Most orders
3,1,Chocolate Sandwich Cookies,61,19,5.800781,9228,79603,2,2,10,30.0,2,0,both,Mid-range product,Regularly busy,Regularly busy,Most orders
4,1,Chocolate Sandwich Cookies,61,19,5.800781,9273,50005,1,1,15,NaN,30,0,both,Mid-range product,Regularly busy,Next_busiest_day,Most orders

# Group by product name

In [7]:
df.groupby('product_name')

# Group on department_id by using the mean on order_number

In [8]:
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                15.577493
2                17.320781
3                16.084944
4                17.530458
5                14.763075
6                16.658449
7                17.031590
8                15.076662
9                15.447580
10               18.681852
11               15.447411
12               14.327957
13               16.548642
14               16.960241
15               16.121948
16               17.800887
17               15.593633
18               19.674252
19               16.899756
20               16.255442
21               25.535479

# Add min and max now

In [9]:
df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
1                15.577493   1  99
2                17.320781   1  96
3                16.084944   1  99
4                17.530458   1  99
5                14.763075   1  99
6                16.658449   1  99
7                17.031590   1  99
8                15.076662   1  98
9                15.447580   1  99
10               18.681852   1  99
11               15.447411   1  99
12               14.327957   1  99
13               16.548642   1  99
14               16.960241   1  99
15               16.121948   1  99
16               17.800887   1  99
17               15.593633   1  99
18               19.674252   1  99
19               16.899756   1  99
20               16.255442   1  99
21               25.535479   1  98

# Create a new column max_order that will be defined by grouping the user_id with the max count of order_number - the max number that each customer has ordered

In [10]:
df_ords_prods_merge['max_order'] = df_ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

C:\Users\valev\AppData\Local\Temp\ipykernel_26576\136815596.py:1: FutureWarning: The provided callable <function max at 0x0000027C4094E3E0> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df_ords_prods_merge['max_order'] = df_ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

In [11]:
df_ords_prods_merge.head(100)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order
0,1,Chocolate Sandwich Cookies,61,19,5.800781,1107,38259,2,1,11,7.0,7,0,both,Mid-range product,Regularly busy,Next_busiest_day,Most orders,4
1,1,Chocolate Sandwich Cookies,61,19,5.800781,5319,196224,65,1,14,1.0,3,1,both,Mid-range product,Regularly busy,Next_busiest_day,Most orders,99
2,1,Chocolate Sandwich Cookies,61,19,5.800781,7540,138499,8,0,14,7.0,4,1,both,Mid-range product,Busiest day,Busiest day,Most orders,23
3,1,Chocolate Sandwich Cookies,61,19,5.800781,9228,79603,2,2,10,30.0,2,0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,5
4,1,Chocolate Sandwich Cookies,61,19,5.800781,9273,50005,1,1,15,NaN,30,0,both,Mid-range product,Regularly busy,Next_busiest_day,Most orders,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1,Chocolate Sandwich Cookies,61,19,5.800781,197804,84766,22,1,14,5.0,2,1,both,Mid-range product,Regularly busy,Next_busiest_day,Most orders,41
96,1,Chocolate Sandwich Cookies,61,19,5.800781,199870,55962,18,0,18,12.0,1,1,both,Mid-range product,Busiest day,Busiest day,Average orders,22
97,1,Chocolate Sandwich Cookies,61,19,5.800781,200390,1540,4,2,0,7.0,10,0,both,Mid-range product,Regularly busy,Regularly busy,Fewest orders,28
98,1,Chocolate Sandwich Cookies,61,19,5.800781,204112,65051,12,4,10,30.0,6,0,both,Mid-range product,Least busy,Least busy,Most orders,16
99,1,Chocolate Sandwich Cookies,61,19,5.800781,205631,166360,7,3,8,12.0,16,0,both,Mid-range product,Regularly busy,Next_slowest_day,Average orders,12

# Use the following to avoid jupyter breaking the 100 rows of head that it was asked for

In [12]:
pd.options.display.max_rows = None

In [13]:
df_ords_prods_merge.sort_values('user_id', ascending=False).head(100)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order
7868909,13176,Bag of Organic Bananas,24,4,10.296875,3154581,206209,1,3,11,NaN,10,0,both,Mid-range product,Regularly busy,Next_slowest_day,Most orders,13
11541382,19348,Fat Free Milk,84,16,4.601562,2129269,206209,8,3,17,22.0,3,1,both,Low-range product,Regularly busy,Next_slowest_day,Average orders,13
11827771,19734,Classic Mix Variety,107,19,4.800781,1542354,206209,3,5,11,30.0,11,0,both,Low-range product,Regularly busy,Regularly busy,Most orders,13
26340514,40992,Chopped Tomatoes,81,15,1.799805,2129269,206209,8,3,17,22.0,9,1,both,Low-range product,Regularly busy,Next_slowest_day,Average orders,13
14855312,23892,Original High Efficiency Liquid Laundry Detergent,75,17,9.101562,2558525,206209,9,4,15,22.0,2,1,both,Mid-range product,Least busy,Least busy,Most orders,13
5520451,9405,Calcium Enriched 100% Lactose Free Fat Free Milk,91,16,11.500000,626363,206209,12,1,12,18.0,3,1,both,Mid-range product,Regularly busy,Next_busiest_day,Most orders,13
7690069,13176,Bag of Organic Bananas,24,4,10.296875,1542354,206209,3,5,11,30.0,6,1,both,Mid-range product,Regularly busy,Regularly busy,Most orders,13
26425565,41213,French Loaf,112,3,4.800781,3154581,206209,1,3,11,NaN,3,0,both,Low-range product,Regularly busy,Next_slowest_day,Most orders,13
15744474,24852,Banana,24,4,12.296875,2266710,206209,10,5,18,29.0,7,0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,13
16489215,25837,Mini Babybel Light Semisoft Edam Cheeses,21,16,3.800781,3154581,206209,1,3,11,NaN,13,0,both,Low-range product,Regularly busy,Next_slowest_day,Most orders,13
1257586,2519,Rice Krispies Cereal,121,14,1.099609,1542354,206209,3,5,11,30.0,9,0,both,Low-range product,Regularly busy,Regularly busy,Most orders,13
3904055,6825,Breakfast Veggie Bacon Strips,42,1,4.000000,550836,206209,7,2,13,9.0,7,0,both,Low-range product,Regularly busy,Regularly busy,Most orders,13
7774704,13176,Bag of Organic Bananas,24,4,10.296875,2307371,206209,5,4,15,3.0,3,1,both,Mid-range product,Least busy,Least busy,Most orders,13
5520385,9405,Calcium Enriched 100% Lactose Free Fat Free Milk,91,16,11.500000,550836,206209,7,2,13,9.0,2,1,both,Mid-range product,Regularly busy,Regularly busy,Most orders,13
11950517,20073,Jazz Apple,24,4,6.398438,3154581,206209,1,3,11,NaN,9,0,both,Mid-range product,Regularly busy,Next_slowest_day,Most orders,13
26423115,41213,French Loaf,112,3,4.800781,688306,206209,4,1,10,30.0,1,1,both,Low-range product,Regularly busy,Next_busiest_day,Most orders,13
397794,755,Skim Milk sharp Cheddar Cheese Singles,21,16,9.000000,550836,206209,7,2,13,9.0,3,0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,13
28430455,44325,Elbow Macaroni Pasta,131,9,1.799805,550836,206209,7,2,13,9.0,8,0,both,Low-range product,Regularly busy,Regularly busy,Most orders,13
7119318,12376,Sourdough Demi Baguette,112,3,11.500000,2129269,206209,8,3,17,22.0,8,0,both,Mid-range product,Regularly busy,Next_slowest_day,Average orders,13
5521631,9405,Calcium Enriched 100% Lactose Free Fat Free Milk,91,16,11.500000,1889163,206209,2,3,17,7.0,2,1,both,Mid-range product,Regularly busy,Next_slowest_day,Average orders,13
14854747,23892,Original High Efficiency Liquid Laundry Detergent,75,17,9.101562,1542354,206209,3,5,11,30.0,14,0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,13
2216594,4591,Quick 1 Minute Oatmeal,130,14,1.200195,1889163,206209,2,3,17,7.0,4,0,both,Low-range product,Regularly busy,Next_slowest_day,Average orders,13
14864817,23909,2% Reduced Fat Milk,84,16,9.203125,550836,206209,7,2,13,9.0,9,0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,13
3909093,6846,Diet Pepsi Pack,77,7,11.296875,550836,206209,7,2,13,9.0,1,1,both,Mid-range product,Regularly busy,Regularly busy,Most orders,13
26686996,41665,Organic Mexican Blend Finely Shredded Cheese,21,16,4.699219,688306,206209,4,1,10,30.0,5,0,both,Low-range product,Regularly busy,Next_busiest_day,Most orders,13
31752610,48697,Canola Oil,19,13,8.296875,550836,206209,7,2,13,9.0,6,0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,13
3909161,6846,Diet Pepsi Pack,77,7,11.296875,626363,206209,12,1,12,18.0,1,1,both,Mid-range product,Regularly busy,Next_busiest_day,Most orders,13
26424315,41213,French Loaf,112,3,4.800781,1889163,206209,2,3,17,7.0,1,1,both,Low-range product,Regularly busy,Next_slowest_day,Average orders,13
5851588,10070,Organic 1% Low Fat Milk,84,16,5.898438,1542354,206209,3,5,11,30.0,10,0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,13
5521304,9405,Calcium Enriched 100% Lactose Free Fat Free Milk,91,16,11.500000,1542354,206209,3,5,11,30.0,3,1,both,Mid-range product,Regularly busy,Regularly busy,Most orders,13
12217229,20590,Disinfecting Wipes Fresh Scent,114,17,5.898438,626363,206209,12,1,12,18.0,15,0,both,Mid-range product,Regularly busy,Next_busiest_day,Most orders,13
25968631,40396,Guacamole,67,20,3.599609,1542354,206209,3,5,11,30.0,5,1,both,Low-range product,Regularly busy,Regularly busy,Most orders,13
11539021,19348,Fat Free Milk,84,16,4.601562,1854736,206209,11,4,10,30.0,5,1,both,Low-range product,Least busy,Least busy,Most orders,13
31785567,48742,Quick 1 Minute Whole Grain Oats,130,14,5.898438,550836,206209,7,2,13,9.0,5,0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,13
31785609,48742,Quick 1 Minute Whole Grain Oats,130,14,5.898438,626363,206209,12,1,12,18.0,13,1,both,Mid-range product,Regularly busy,Next_busiest_day,Most orders,13
14854240,23892,Original High Efficiency Liquid Laundry Detergent,75,17,9.101562,688306,206209,4,1,10,30.0,16,1,both,Mid-range product,Regularly busy,Next_busiest_day,Most orders,13
11949972,20073,Jazz Apple,24,4,6.398438,1889163,206209,2,3,17,7.0,3,1,both,Mid-range product,Regularly busy,Next_slowest_day,Average orders,13
3158445,5622,Cocktail Tomatoes on the Vine,123,4,8.796875,626363,206209,12,1,12,18.0,18,0,both,Mid-range product,Regularly busy,Next_busiest_day,Most orders,13
10261804,17500,Cinch Sak Extra Large 33 Gallon Trash Bags,60,17,2.099609,2129269,206209,8,3,17,22.0,6,0,both,Low-range product,Regularly busy,Next_slowest_day,Average orders,13
26423058,41213,French Loaf,112,3,4.800781,626363,206209,12,1,12,18.0,5,1,both,Low-range product,Regularly busy,Next_busiest_day,Most orders,13
14404058,23039,Fat Free Cream Cheese,108,16,3.400391,3154581,206209,1,3,11,NaN,7,0,both,Low-range product,Regularly busy,Next_slowest_day,Most orders,13
11528994,19348,Fat Free Milk,84,16,4.601562,688306,206209,4,1,10,30.0,15,0,both,Low-range product,Regularly busy,Next_busiest_day,Most orders,13
28205206,43961,Organic Peeled Whole Baby Carrots,123,4,3.800781,2129269,206209,8,3,17,22.0,2,1,both,Low-range product,Regularly busy,Next_slowest_day,Average orders,13
4514733,8006,Chopped Organic Garlic,110,13,6.101562,688306,206209,4,1,10,30.0,13,0,both,Mid-range product,Regularly busy,Next_busiest_day,Most orders,13
3910532,6846,Diet Pepsi Pack,77,7,11.296875,2129269,206209,8,3,17,22.0,5,1,both,Mid-range product,Regularly busy,Next_slowest_day,Average orders,13
26024895,40534,In Rich Tomato Sauce Vegetarian Beans,59,15,13.296875,1542354,206209,3,5,11,30.0,4,1,both,Mid-range product,Regularly busy,Regularly busy,Most orders,13
15517366,24852,Banana,24,4,12.296875,626363,206209,12,1,12,18.0,2,1,both,Mid-range product,Regularly busy,Next_busiest_day,Most orders,13
14403542,23039,Fat Free Cream Cheese,108,16,3.400391,626363,206209,12,1,12,18.0,19,1,both,Low-range product,Regularly busy,Next_busiest_day,Most orders,13
9466557,16168,Large Organic Omega3 Brown Eggs,86,16,11.796875,2977660,206209,13,1,12,7.0,3,1,both,Mid-range product,Regularly busy,Next_busiest_day,Most orders,13
25894469,40310,Oven Roasted Turkey Breast,96,20,1.900391,1854736,206209,11,4,10,30.0,7,0,both,Low-range product,Least busy,Least busy,Most orders,13
11528453,19348,Fat Free Milk,84,16,4.601562,626363,206209,12,1,12,18.0,4,1,both,Low-range product,Regularly busy,Next_busiest_day,Most orders,13
3910955,6846,Diet Pepsi Pack,77,7,11.296875,2558525,206209,9,4,15,22.0,3,1,both,Mid-range product,Least busy,Least busy,Most orders,13
8864198,14870,Icelandic Style Fat Free Plain Yogurt,120,16,2.099609,2129269,206209,8,3,17,22.0,11,0,both,Low-range product,Regularly busy,Next_slowest_day,Average orders,13
3910674,6846,Diet Pepsi Pack,77,7,11.296875,2266710,206209,10,5,18,29.0,2,1,both,Mid-range product,Regularly busy,Regularly busy,Average orders,13
14710962,23594,Medium Salsa,51,13,3.699219,3154581,206209,1,3,11,NaN,12,0,both,Low-range product,Regularly busy,Next_slowest_day,Most orders,13
3911476,6846,Diet Pepsi Pack,77,7,11.296875,3154581,206209,1,3,11,NaN,1,0,both,Mid-range product,Regularly busy,Next_slowest_day,Most orders,13
16305710,25544,Fresh Cut Golden Sweet Whole Kernel Corn,81,15,5.500000,688306,206209,4,1,10,30.0,8,0,both,Mid-range product,Regularly busy,Next_busiest_day,Most orders,13
25110627,39216,Original Multigrain Spoonfuls Cereal,121,14,3.300781,2977660,206209,13,1,12,7.0,4,0,both,Low-range product,Regularly busy,Next_busiest_day,Most orders,13
9463439,16168,Large Organic Omega3 Brown Eggs,86,16,11.796875,626363,206209,12,1,12,18.0,16,0,both,Mid-range product,Regularly busy,Next_busiest_day,Most orders,13
26024993,40534,In Rich Tomato Sauce Vegetarian Beans,59,15,13.296875,3154581,206209,1,3,11,NaN,6,0,both,Mid-range product,Regularly busy,Next_slowest_day,Most orders,13
14707914,23594,Medium Salsa,51,13,3.699219,626363,206209,12,1,12,18.0,14,1,both,Low-range product,Regularly busy,Next_busiest_day,Most orders,13
14707997,23594,Medium Salsa,51,13,3.699219,688306,206209,4,1,10,30.0,3,1,both,Low-range product,Regularly busy,Next_busiest_day,Most orders,13
3909967,6846,Diet Pepsi Pack,77,7,11.296875,1542354,206209,3,5,11,30.0,1,1,both,Mid-range product,Regularly busy,Regularly busy,Most orders,13
21508614,33129,Classic Hummus,67,20,1.299805,626363,206209,12,1,12,18.0,9,1,both,Low-range product,Regularly busy,Next_busiest_day,Most orders,13
3810353,6567,Chocolate Peanut Butter Protein Bar,3,19,4.898438,2977660,206209,13,1,12,7.0,8,0,both,Low-range product,Regularly busy,Next_busiest_day,Most orders,13
21636244,33351,Light Multi-Grain English Muffins,93,3,6.398438,626363,206209,12,1,12,18.0,17,0,both,Mid-range product,Regularly busy,Next_busiest_day,Most orders,13
945121,1979,Pure Coconut Milk,66,6,11.101562,688306,206209,4,1,10,30.0,11,0,both,Mid-range product,Regularly busy,Next_busiest_day,Most orders,13
7595224,13176,Bag of Organic Bananas,24,4,10.296875,688306,206209,4,1,10,30.0,2,1,both,Mid-range product,Regularly busy,Next_busiest_day,Most orders,13
14709033,23594,Medium Salsa,51,13,3.699219,1542354,206209,3,5,11,30.0,8,1,both,Low-range product,Regularly busy,Regularly busy,Most orders,13
20239321,31130,Sea Salt Flakes Original,104,13,6.300781,2266710,206209,10,5,18,29.0,9,0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,13
3910254,6846,Diet Pepsi Pack,77,7,11.296875,1854736,206209,11,4,10,30.0,1,1,both,Mid-range product,Least busy,Least busy,Most orders,13
3640962,6187,Raisin Bran Cereal,121,14,5.500000,3186442,206209,6,0,16,3.0,2,1,both,Mid-range product,Busiest day,Busiest day,Average orders,13
3910285,6846,Diet Pepsi Pack,77,7,11.296875,1889163,206209,2,3,17,7.0,8,1,both,Mid-range product,Regularly busy,Next_slowest_day,Average orders,13
5521592,9405,Calcium Enriched 100% Lactose Free Fat Free Milk,91,16,11.500000,1854736,206209,11,4,10,30.0,2,1,both,Mid-range product,Least busy,Least busy,Most orders,13
26338569,40992,Chopped Tomatoes,81,15,1.799805,550836,206209,7,2,13,9.0,4,1,both,Low-range product,Regularly busy,Regularly busy,Most orders,13
31578210,48370,Sensitive Toilet Paper,54,17,7.398438,1854736,206209,11,4,10,30.0,8,0,both,Mid-range product,Least busy,Least busy,Most orders,13
16486090,25837,Mini Babybel Light Semisoft Edam Cheeses,21,16,3.800781,1542354,206209,3,5,11,30.0,7,1,both,Low-range product,Regularly busy,Regularly busy,Most orders,13
5522029,9405,Calcium Enriched 100% Lactose Free Fat Free Milk,91,16,11.500000,2307371,206209,5,4,15,3.0,1,1,both,Mid-range product,Least busy,Least busy,Most orders,13
8795529,14727,Yellow Onion,123,4,3.199219,626363,206209,12,1,12,18.0,20,0,both,Low-range product,Regularly busy,Next_busiest_day,Most orders,13
8902828,14901,Raisins,117,19,2.000000,3154581,206209,1,3,11,NaN,5,0,both,Low-range product,Regularly busy,Next_slowest_day,Most orders,13
25977061,40396,Guacamole,67,20,3.599609,3154581,206209,1,3,11,NaN,4,0,both,Low-range product,Regularly busy,Next_slowest_day,Most orders,13
16486755,25837,Mini Babybel Light Semisoft Edam Cheeses,21,16,3.800781,1889163,206209,2,3,17,7.0,5,1,both,Low-range product,Regularly busy,Next_slowest_day,Average orders,13
14817116,23800,Whole Grain Cereal,121,14,6.199219,2266710,206209,10,5,18,29.0,6,0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,13
26424283,41213,French Loaf,112,3,4.800781,1854736,206209,11,4,10,30.0,3,1,both,Low-range product,Least busy,Least busy,Most orders,13
15687478,24852,Banana,24,4,12.296875,1854736,206209,11,4,10,30.0,4,1,both,Mid-range product,Least busy,Least busy,Most orders,13
5521985,9405,Calcium Enriched 100% Lactose Free Fat Free Milk,91,16,11.500000,2266710,206209,10,5,18,29.0,1,1,both,Mid-range product,Regularly busy,Regularly busy,Average orders,13
12348496,20842,Total 0% Greek Yogurt,120,16,13.601562,3154581,206209,1,3,11,NaN,11,0,both,Mid-range product,Regularly busy,Next_slowest_day,Most orders,13
28181762,43961,Organic Peeled Whole Baby Carrots,123,4,3.800781,688306,206209,4,1,10,30.0,12,0,both,Low-range product,Regularly busy,Next_busiest_day,Most orders,13
24161509,37654,Butter with Canola Oil Spread,36,16,12.601562,1542354,206209,3,5,11,30.0,13,0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,13
14816800,23800,Whole Grain Cereal,121,14,6.199219,626363,206209,12,1,12,18.0,11,1,both,Mid-range product,Regularly busy,Next_busiest_day,Most orders,13
9281667,15700,Cheddar Cheese Nut Thins Cracker Snacks,78,19,2.300781,1854736,206209,11,4,10,30.0,6,1,both,Low-range product,Least busy,Least busy,Most orders,13
1122500,2295,Yellow Bell Pepper,83,4,6.500000,688306,206209,4,1,10,30.0,14,0,both,Mid-range product,Regularly busy,Next_busiest_day,Most orders,13
6821054,11791,Chorizo,96,20,4.398438,688306,206209,4,1,10,30.0,10,0,both,Low-range product,Regularly busy,Next_busiest_day,Most orders,13
9280324,15700,Cheddar Cheese Nut Thins Cracker Snacks,78,19,2.300781,626363,206209,12,1,12,18.0,6,1,both,Low-range product,Regularly busy,Next_busiest_day,Most orders,13
8533758,14197,Tomato Paste,9,9,5.601562,3186442,206209,6,0,16,3.0,1,0,both,Mid-range product,Busiest day,Busiest day,Average orders,13
5522819,9405,Calcium Enriched 100% Lactose Free Fat Free Milk,91,16,11.500000,3154581,206209,1,3,11,NaN,2,0,both,Mid-range product,Regularly busy,Next_slowest_day,Most orders,13
2145082,4461,Organic Raw Unfiltered Apple Cider Vinegar,19,13,14.296875,550836,206209,7,2,13,9.0,10,0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,13
8289217,13838,Natural Free & Clear Dish Liquid,74,17,3.800781,626363,206209,12,1,12,18.0,12,1,both,Low-range product,Regularly busy,Next_busiest_day,Most orders,13
7728445,13176,Bag of Organic Bananas,24,4,10.296875,1889163,206209,2,3,17,7.0,7,1,both,Mid-range product,Regularly busy,Next_slowest_day,Average orders,13
8293572,13838,Natural Free & Clear Dish Liquid,74,17,3.800781,2266710,206209,10,5,18,29.0,8,0,both,Low-range product,Regularly busy,Regularly busy,Average orders,13

# Assign loyalty values to the max_order column where if the max is above 40 the string is 'loyal customer', if more than ten and equal/less than 40 then 'regular customer', and if less than 10 then 'new customer"

In [14]:
df_ords_prods_merge.loc[df_ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [15]:
df_ords_prods_merge.loc[(df_ords_prods_merge['max_order'] <= 40) & (df_ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [16]:
df_ords_prods_merge.loc[df_ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [17]:
df_ords_prods_merge['loyalty_flag'].value_counts(dropna=False)

loyalty_flag
Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: count, dtype: int64

In [18]:
df_ords_prods_merge[['user_id', 'loyalty_flag', 'order_number']].head(60)

    user_id      loyalty_flag  order_number
0     38259      New customer             2
1    196224    Loyal customer            65
2    138499  Regular customer             8
3     79603      New customer             2
4     50005  Regular customer             1
5    108919    Loyal customer            46
6     63782      New customer             4
7    170451      New customer             5
8    106854    Loyal customer            28
9    181127  Regular customer            10
10   106519  Regular customer            18
11   145505    Loyal customer            64
12   139923  Regular customer            16
13   110984  Regular customer             2
14   180719    Loyal customer            84
15   142388  Regular customer             7
16   200356  Regular customer            11
17     4122  Regular customer            11
18   162394      New customer             2
19   148255  Regular customer            18
20   205157  Regular customer            11
21   181127  Regular customer             3
22    92648  Regular customer             8
23    30345      New customer             6
24    50898  Regular customer            28
25    57996    Loyal customer            12
26    77956    Loyal customer            90
27    22561      New customer             4
28   199115  Regular customer            20
29    91160    Loyal customer            32
30    50150  Regular customer            17
31    38748  Regular customer            16
32    65777    Loyal customer            47
33   134728  Regular customer            18
34    11119  Regular customer            18
35    45784  Regular customer             4
36    21054      New customer             3
37   196224    Loyal customer            23
38   102960    Loyal customer            21
39   113429  Regular customer            17
40   111982    Loyal customer            76
41   144159  Regular customer             3
42    72224    Loyal customer            12
43    23234  Regular customer            10
44   131925  Regular customer             8
45    16057  Regular customer             2
46   124716      New customer             5
47    60380  Regular customer            26
48   197324  Regular customer            12
49   157800  Regular customer             9
50    48228      New customer             1
51    23513  Regular customer             5
52    95847    Loyal customer            44
53   101727  Regular customer            28
54   139923  Regular customer            19
55    11448  Regular customer            20
56   162795  Regular customer             6
57   134130  Regular customer            13
58   178504  Regular customer             8
59    80421      New customer             8